### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by jhen0409** [jhen0409/react-chrome-extension-boilerplate#8]
- [ ] Upgrade Babel to 6
- [ ] Upgrade React/Redux
  - [ ] React 0.14
  - [ ] Redux 3 & Redux DevTools
  - [ ] Use [redux-devtools-extension](https://github.com/zalmoxisus/redux-devtools-extension)
- [ ] Use [css-modules](https://github.com/css-modules/css-modules)
  - [ ] Rewrite todomvc-app-css
  - [ ] inject page show todomvc example
- [ ] Use [crx](https://github.com/oncletom/crx) to pack Chrome Extension.
